repos:
  - repo: local
    hooks:
      - id: sqlx-prepare
        name: sqlx prepare
        language: script
        entry: ./script/pre-commit/sqlx-prepare.sh
        pass_filenames: false
      - id: backend-check
        name: backend check
        language: script
        entry: ./script/pre-commit/backend-check.sh
        pass_filenames: false
      - id: frontend-lint
        name: frontend lint
        language: script
        entry: ./script/pre-commit/frontend-lint.sh
        pass_filenames: false
